name: Test actions

on:
  - push

jobs:
  sanitize_docker_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: sanitize_docker_tag
        uses: ./sanitize_docker_tag
        with:
          tag: //I'M " ` unsanitized .,-/
      - name:
        run: echo ${{ steps.sanitize_docker_tag.outputs.sanitized_tag }}
