name: Test actions

on:
  - push

jobs:
  sanitize-text:
    runs-on: ubuntu-latest
    steps:
      - id: sanitize-text
        uses: condenast/actions/sanitize-text@sanitize-text
        with:
          text: //I'M " ` unsanitized .,-/
      - name: echo sanitized text
        run: echo ${{ steps.sanitize-text.outputs.sanitized_text }}
