name: Test actions

on:
  - push

jobs:
  sanitize-docker-tag:
    runs-on: ubuntu-latest
    steps:
      - id: sanitize-docker-tag
        uses: condenast/actions/sanitize-docker-tag@master
        with:
          tag: //I'M " ` unsanitized .,-/
      - name: echo sanitized tag
        run: echo ${{ steps.sanitize-docker-tag.outputs.sanitized_tag }}
